const familyData = {
  family: [
    {
      id: 1,
      name: "Poduri Reddappa",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: null,
      spouseId: null,
      generation: 1,
      avatar: "PR",
    },
    {
      id: 2,
      name: "Poduri Gangayya",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 1,
      spouseId: null,
      generation: 2,
      avatar: "PG",
    },
    {
      id: 3,
      name: "Poduri Kotayya",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 2,
      spouseId: null,
      generation: 3,
      avatar: "PS",
    },
    {
      id: 4,
      name: "Poduri Seshayya",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 2,
      spouseId: 5,
      generation: 3,
      avatar: "PS",
    },
    {
      id: 5,
      name: "Poduri Aadamma",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: null,
      spouseId: 4,
      generation: 3,
      avatar: "PA",
    },
    {
      id: 6,
      name: "Poduri Subbanna",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 2,
      spouseId: 7,
      generation: 3,
      avatar: "PS",
    },
    {
      id: 7,
      name: "Poduri Seshamma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 6,
      generation: 3,
      avatar: "PS",
    },
    {
      id: 8,
      name: "Poduri Meerayya",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 3,
      spouseId: 9,
      generation: 4,
      avatar: "PM",
    },
    {
      id: 9,
      name: "Poduri Rama Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: null,
      spouseId: 8,
      generation: 4,
      avatar: "PRL",
    },
    {
      id: 10,
      name: "Poduri Appanna",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 4,
      spouseId: 11,
      generation: 4,
      avatar: "PA",
    },
    {
      id: 11,
      name: "Poduri Parvati",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: null,
      spouseId: 10,
      generation: 4,
      avatar: "PA",
    },
    {
      id: 12,
      name: "Poduri Gangayya",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 4,
      spouseId: 13,
      generation: 4,
      avatar: "PG",
    },
    {
      id: 13,
      name: "Poduri Mahalakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 12,
      generation: 4,
      avatar: "PM",
    },
    {
      id: 14,
      name: "Poduri Sathyam",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 4,
      spouseId: 15,
      generation: 4,
      avatar: "PS",
    },
    {
      id: 15,
      name: "Poduri Pullamma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 14,
      generation: 4,
      avatar: "PP",
    },
    {
      id: 16,
      name: "Poduri Somanna",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 4,
      spouseId: 17,
      generation: 4,
      avatar: "PS",
    },
    {
      id: 17,
      name: "Poduri Papamma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 16,
      generation: 4,
      avatar: "PP",
    },
    {
      id: 18,
      name: "Poduri Chinna Appanna",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 6,
      spouseId: 19,
      generation: 4,
      avatar: "PCA",
    },
    {
      id: 19,
      name: "Poduri Narsamma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 18,
      generation: 4,
      avatar: "PN",
    },
    {
      id: 20,
      name: "Poduri Sesha Rao", // continue
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 6,
      spouseId: 21,
      generation: 4,
      avatar: "PSR",
    },
    {
      id: 21,
      name: "Poduri Satyanarayana Amma (Chanti Amma)",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 20,
      generation: 4,
      avatar: "PSA",
    },
    {
      id: 22,
      name: "Poduri Koteswara Rao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 8,
      spouseId: 23,
      generation: 4,
      avatar: "PKR",
    },
    {
      id: 23,
      name: "Poduri Prabhavathi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 22,
      generation: 4,
      avatar: "PP",
    },
    {
      id: 24,
      name: "Poduri Satyanarayana",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 8,
      spouseId: 25,
      generation: 4,
      avatar: "PS",
    },
    {
      id: 25,
      name: "Poduri Pandu Ranganayakamma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 24,
      generation: 4,
      avatar: "PPR",
    },
    {
      id: 26,
      name: "Poduri Suryakantham",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 8,
      spouseId: null,
      generation: 4,
      avatar: "PA",
    },
    {
      id: 27,
      name: "Poduri Nagaratnam",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 8,
      spouseId: null,
      generation: 4,
      avatar: "PN",
    },
    {
      id: 28,
      name: "Poduri Krishnaveni",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 8,
      spouseId: null,
      generation: 4,
      avatar: "PK",
    },
    {
      id: 29,
      name: "Poduri Sesharao",
      birthDate: "1942-01-10",
      deathDate: "",
      gender: "male",
      parentId: 10,
      spouseId: 30,
      generation: 5,
      avatar: "PA",
    },
    {
      id: 30,
      name: "Poduri Nagamani",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 29,
      generation: 5,
      avatar: "PN",
    },
    {
      id: 31,
      name: "Poduri Seeta Mahalakshmi",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 10,
      spouseId: null,
      generation: 5,
      avatar: "PSM",
    },
    {
      id: 32,
      name: "Poduri Satyanarayana",
      birthDate: "1952-12-18",
      deathDate: "",
      gender: "male",
      parentId: null,
      spouseId: 33,
      generation: 5,
      avatar: "PA",
    },
    {
      id: 33,
      name: "Poduri kameswari",
      birthDate: "1954",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 32,
      generation: 5,
      avatar: "PK",
    },
    {
      id: 34,
      name: "Poduri Bhaskara Rao",
      birthDate: "1953-12-15",
      deathDate: "2023",
      gender: "male",
      parentId: 10,
      spouseId: 35,
      generation: 5,
      avatar: "PBR",
    },
    {
      id: 35,
      name: "Poduri Jaya Kumari",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 34,
      generation: 5,
      avatar: "PJK",
    },
    {
      id: 36,
      name: "Poduri Lakshmi",
      birthDate: "1956",
      deathDate: null,
      gender: "female",
      parentId: 10,
      spouseId: null,
      generation: 5,
      avatar: "PL",
    },
    {
      id: 37,
      name: "Poduri Nagamani",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 10,
      spouseId: null,
      generation: 5,
      avatar: "PN",
    },
    {
      id: 38,
      name: "Poduri Venkateswara Rao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 10,
      spouseId: 39,
      generation: 5,
      avatar: "PVR",
    },
    {
      id: 39,
      name: "Poduri Anantha Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 38,
      generation: 5,
      avatar: "PAL",
    },
    {
      id: 40,
      name: "Poduri Suryakantham",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 12,
      spouseId: null,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 41,
      name: "Poduri Seetamahalakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 12,
      spouseId: null,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 42,
      name: "Poduri Sathyavati",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 12,
      spouseId: null,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 43,
      name: "Poduri Bhaskara Rao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 12,
      spouseId: 45,
      generation: 5,
      avatar: "PBR",
    },
    {
      id: 44,
      name: "Poduri Bujinga Rao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 12,
      spouseId: 45,
      generation: 5,
      avatar: "PBR",
    },
    {
      id: 45,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 44,
      generation: 5,
      avatar: "PL",
    },
    {
      id: 46,
      name: "Poduri Satyanarayana",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 14,
      spouseId: 47,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 47,
      name: "Poduri Bhaskaram",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 46,
      generation: 5,
      avatar: "PB",
    },
    {
      id: 48,
      name: "Poduri Appa Rao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 16,
      spouseId: 49,
      generation: 5,
      avatar: "PAR",
    },
    {
      id: 49,
      name: "Poduri Mangatayaru",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 48,
      generation: 5,
      avatar: "PM",
    },
    {
      id: 50,
      name: "Poduri Tulasi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 16,
      spouseId: null,
      generation: 5,
      avatar: "PT",
    },
    {
      id: 51,
      name: "Poduri Aaadi Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 16,
      spouseId: null,
      generation: 5,
      avatar: "PAL",
    },
    {
      id: 52,
      name: "Poduri Jayamma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 22,
      spouseId: null,
      generation: 5,
      avatar: "PJ",
    },
    {
      id: 53,
      name: "Poduri Kusuma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 22,
      spouseId: null,
      generation: 5,
      avatar: "PK",
    },
    {
      id: 54,
      name: "Poduri Sree Devi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 22,
      spouseId: null,
      generation: 5,
      avatar: "PSD",
    },
    {
      id: 55,
      name: "Poduri Sreenivas Rao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 22,
      spouseId: null,
      generation: 4,
      avatar: "PS",
    },
    {
      id: 56,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 24,
      spouseId: null,
      generation: 5,
      avatar: "PL",
    },
    {
      id: 57,
      name: "Poduri Ramalakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 24,
      spouseId: null,
      generation: 5,
      avatar: "PR",
    },
    {
      id: 58,
      name: "Poduri Sree Devi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 24,
      spouseId: null,
      generation: 5,
      avatar: "PSD",
    },
    {
      id: 59,
      name: "Poduri Nagababu",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 24,
      spouseId: null,
      generation: 5,
      avatar: "PN",
    },
    {
      id: 60,
      name: "Poduri Satyanarayana",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 18,
      spouseId: 61,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 61,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 60,
      generation: 5,
      avatar: "PL",
    },
    {
      id: 62,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 18,
      spouseId: null,
      generation: 5,
      avatar: "PL",
    },
    {
      id: 63,
      name: "Poduri Satyavathi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 18,
      spouseId: null,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 62,
      name: "Poduri Venkateswara Rao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 20,
      spouseId: 63,
      generation: 5,
      avatar: "PVR",
    },
    {
      id: 63,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 20,
      spouseId: 63,
      generation: 5,
      avatar: "PL",
    },
    {
      id: 64,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 20,
      spouseId: null,
      generation: 5,
      avatar: "PL",
    },
    {
      id: 65,
      name: "Poduri Subbarao",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 20,
      spouseId: 66,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 66,
      name: "Poduri Satyavati",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 65,
      generation: 5,
      avatar: "PS",
    },
    {
      id: 67,
      name: "Poduri Veerraju",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 20,
      spouseId: null,
      generation: 5,
      avatar: "PV",
    },
    {
      id: 68,
      name: "Poduri Nagamani",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: null,
      spouseId: 67,
      generation: 5,
      avatar: "PN",
    },
    {
      id: 69,
      name: "Poduri Bujjamma",
      birthDate: "",
      deathDate: "",
      gender: "female",
      parentId: 20,
      spouseId: null,
      generation: 5,
      avatar: "PB",
    },
    {
      id: 70,
      name: "Poduri Rama Raju",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 20,
      spouseId: 71,
      generation: 5,
      avatar: "PRR",
    },
    {
      id: 71,
      name: "Poduri Govardhana",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: null,
      spouseId: 70,
      generation: 5,
      avatar: "PG",
    },
    {
      id: 72,
      name: "Poduri Raju",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: 20,
      spouseId: null,
      generation: 5,
      avatar: "PR",
    },
    {
      id: 73,
      name: "Poduri Rama Krishna",
      birthDate: "1964-11-12",
      deathDate: null,
      gender: "male",
      parentId: 29,
      spouseId: 74,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094831/krishna_lpkq2s.jpg",
    },
    {
      id: 74,
      name: "Poduri Anjali Devi",
      birthDate: "1969-08-11",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 73,
      generation: 6,
      avatar: "PAD",
    },
    {
      id: 75,
      name: "Poduri Naga Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 29,
      spouseId: null,
      generation: 6,
      avatar: "PNL",
    },
    {
      id: 76,
      name: "Poduri Rama Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 29,
      spouseId: null,
      generation: 6,
      avatar: "PRL",
    },
    {
      id: 76,
      name: "Poduri Lakshmana Rao (Peesu)",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 29,
      spouseId: 77,
      generation: 6,
      avatar: "PLR",
    },
    {
      id: 77,
      name: "Poduri Padma",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 29,
      spouseId: 76,
      generation: 6,
      avatar: "PP",
    },
    {
      id: 78,
      name: "Poduri Lakshmi Narayana",
      birthDate: "1973-09-19",
      deathDate: null,
      gender: "male",
      parentId: 29,
      spouseId: 79,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105581/IMG-20250628-WA0003_ybu2au.jpg",
    },
    {
      id: 79,
      name: "Poduri Venkata Lakshmi",
      birthDate: "1982-05-25",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 78,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105582/IMG-20250628-WA0001_qumq4v.jpg",
    },
    {
      id: 80,
      name: "Poduri Veera Venkata Mallikarjuna Rao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 29,
      spouseId: 81,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751112070/IMG_20250628_173021_fpeqom.jpg",
    },
    {
      id: 81,
      name: "Poduri Vijaya Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 80,
      generation: 6,
      avatar: "PVL",
    },
    {
      id: 82,
      name: "Poduri Venkata Naga Siva Prasad",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 32,
      spouseId: 83,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751128283/IMG_20250628_215938_nmfioq.jpg",
    },
    {
      id: 83,
      name: "Poduri Vara Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 82,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751128282/IMG_20250628_220000_ujw0ed.jpg",
    },
    {
      id: 84,
      name: "Poduri Venkata Apparao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 32,
      spouseId: 85,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751111853/IMG_20250628_172529_jjzgl8.jpg",
    },
    {
      id: 85,
      name: "Poduri Naga Maha Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 84,
      generation: 6,
      avatar: "PNML",
    },
    {
      id: 86,
      name: "Poduri Venkata Surya Prakash Rao",
      birthDate: "1977-12-07",
      deathDate: null,
      gender: "male",
      parentId: 32,
      spouseId: 87,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751126673/IMG_20250628_213359_zsoyoo.png",
    },
    {
      id: 87,
      name: "Poduri Satya Devi",
      birthDate: "1984-06-24",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 86,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751193871/IMG_20250629_151608_aereny.jpg",
    },
    {
      id: 88,
      name: "Poduri Siva Prasad",
      birthDate: "1978-01-08",
      deathDate: null,
      gender: "male",
      parentId: 34,
      spouseId: 89,
      generation: 6,
      avatar: "PSP",
    },
    {
      id: 89,
      name: "Poduri Jaya Lakshmi",
      birthDate: "1985-05-18",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 88,
      generation: 6,
      avatar: "PJL",
    },
    {
      id: 90,
      name: "Poduri Uma Parvati",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 34,
      spouseId: null,
      generation: 6,
      avatar: "PUP",
    },
    {
      id: 91,
      name: "Poduri Mohan Kumar",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 34,
      spouseId: 92,
      generation: 6,
      avatar: "PMK",
    },
    {
      id: 92,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 91,
      generation: 6,
      avatar: "PL",
    },
    {
      id: 93,
      name: "Poduri Maruti",
      birthDate: "1981-10-09",
      deathDate: null,
      gender: "male",
      parentId: 38,
      spouseId: 94,
      generation: 6,
      avatar: "PM",
    },
    {
      id: 94,
      name: "Poduri Bharathi Devi",
      birthDate: "1987-06-23",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 93,
      generation: 6,
      avatar: "PBV",
    },
    {
      id: 95,
      name: "Poduri Venkata Apparao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 38,
      spouseId: 96,
      generation: 6,
      avatar: "PVA",
    },
    {
      id: 96,
      name: "Poduri Venkata Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 95,
      generation: 6,
      avatar: "PVL",
    },
    {
      id: 97,
      name: "Poduri Kali Vara Prasad",
      birthDate: "1988-06-02",
      deathDate: null,
      gender: "male",
      parentId: 38,
      spouseId: 98,
      generation: 6,
      avatar: "PK",
    },
    {
      id: 98,
      name: "Poduri Lavanya",
      birthDate: "1992-12-06",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 97,
      generation: 6,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751193871/IMG-20250629-WA0019_qpvtoc.jpg",
    },
    {
      id: 99,
      name: "Poduri Madhava",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 46,
      spouseId: null,
      generation: 6,
      avatar: "PM",
    },
    {
      id: 100,
      name: "Poduri Pushpa",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 46,
      spouseId: null,
      generation: 6,
      avatar: "PP",
    },
    {
      id: 101,
      name: "Poduri Someswara Rao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 48,
      spouseId: null,
      generation: 6,
      avatar: "PS",
    },
    {
      id: 102,
      name: "Poduri Rama Devi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 48,
      spouseId: null,
      generation: 6,
      avatar: "PRD",
    },
    {
      id: 103,
      name: "Poduri Rama Devi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 48,
      spouseId: null,
      generation: 6,
      avatar: "PRD",
    },
    {
      id: 104,
      name: "Poduri Sai Teja",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 55,
      spouseId: null,
      generation: 7,
      avatar: "PST",
    },
    {
      id: 105,
      name: "Poduri Pavan",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 59,
      spouseId: null,
      generation: 7,
      avatar: "PP",
    },
    {
      id: 106,
      name: "Poduri Sravan",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 59,
      spouseId: null,
      generation: 7,
      avatar: "PS",
    },
    {
      id: 107,
      name: "Poduri Venkateswara Rao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 60,
      spouseId: 107,
      generation: 6,
      avatar: "PVR",
    },
    {
      id: 108,
      name: "Poduri Satyavati",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 107,
      spouseId: null,
      generation: 6,
      avatar: "PS",
    },
    {
      id: 109,
      name: "Poduri Subramanyam",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 60,
      spouseId: 110,
      generation: 6,
      avatar: "PS",
    },
    {
      id: 110,
      name: "Poduri Nagamani",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 109,
      generation: 6,
      avatar: "PN",
    },
    {
      id: 111,
      name: "Poduri Satyanarayana (Chinnodu)",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 60,
      spouseId: null,
      generation: 6,
      avatar: "PS",
    },
    {
      id: 112,
      name: "Poduri Subbalakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 60,
      spouseId: null,
      generation: 6,
      avatar: "PS",
    },
    {
      id: 113,
      name: "Poduri Seeta Mata",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 60,
      spouseId: null,
      generation: 6,
      avatar: "PSM",
    },

    {
      id: 114,
      name: "Poduri Kumari",
      birthDate: "1989-01-20",
      deathDate: null,
      gender: "female",
      parentId: 73,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094831/kumari_frmg5y.jpg",
    },
    {
      id: 115,
      name: "Poduri Lakshmi",
      birthDate: "1991-03-06",
      deathDate: null,
      gender: "male",
      parentId: 73,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094831/lakshmiakka_fpserf.jpg",
    },
    {
      id: 116,
      name: "Poduri Seshu Kumar",
      birthDate: "1993-02-01",
      deathDate: null,
      gender: "male",
      parentId: 73,
      spouseId: 117,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094830/babi_yp8yfv.jpg",
    },
    {
      id: 117,
      name: "Poduri Pavani",
      birthDate: "1997-01-01",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 116,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094837/pavani_sprtoe.jpg",
    },
    {
      id: 118,
      name: "Poduri Mounika",
      birthDate: "1999-06-28",
      deathDate: null,
      gender: "female",
      parentId: 78,
      spouseId: null,
      generation: 7,
      avatar: "PM",
    },
    {
      id: 119,
      name: "Poduri Sai Lakshmi",
      birthDate: "2002-02-06",
      deathDate: null,
      gender: "female",
      parentId: 78,
      spouseId: null,
      generation: 7,
      avatar: "PC",
    },
    {
      id: 120,
      name: "Poduri Sravani",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 80,
      spouseId: null,
      generation: 7,
      avatar: "PS",
    },
    {
      id: 121,
      name: "Poduri Durga Devi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 80,
      spouseId: null,
      generation: 7,
      avatar: "PDD",
    },
    {
      id: 122,
      name: "Poduri Surya Kala",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 82,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751111847/IMG-20250628-WA0013_bparcf.jpg",
    },
    {
      id: 123,
      name: "Poduri Raja Mouli",
      birthDate: "2004-06-13",
      deathDate: null,
      gender: "male",
      parentId: 82,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105582/IMG_20250628_153929_o8f2wg.jpg",
    },
    {
      id: 124,
      name: "Poduri Manikanta",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 84,
      spouseId: null,
      generation: 7,
      avatar: "PM",
    },
    {
      id: 125,
      name: "Poduri Satya Prakash",
      birthDate: "2004-09-24",
      deathDate: null,
      gender: "male",
      parentId: 84,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751103832/SAVE_20240725_190616_exhspw.jpg",
    },
    {
      id: 126,
      name: "Poduri Yuvaraj Durga Pavan",
      birthDate: "2004-11-15",
      deathDate: null,
      gender: "male",
      parentId: 86,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751111858/Screenshot_2025-06-28-16-39-53-080_com.miui.gallery_hfd4vu.jpg",
    },
    {
      id: 127,
      name: "Poduri Hari Satyanarayana Murthy",
      birthDate: "2007-01-31",
      deathDate: null,
      gender: "male",
      parentId: 86,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105581/IMG-20250628-WA0004_vwvlhu.jpg",
    },
    {
      id: 128,
      name: "Poduri Tharuni Sri Lakshmi Kumari",
      birthDate: "2005-11-02",
      deathDate: null,
      gender: "female",
      parentId: 88,
      spouseId: null,
      generation: 7,
      avatar: "PTSLK",
    },
    {
      id: 129,
      name: "Poduri Kesava Priya Sri Parvathi",
      birthDate: "2010-04-20",
      deathDate: null,
      gender: "female",
      parentId: 88,
      spouseId: null,
      generation: 7,
      avatar: "PKPSP",
    },
    {
      id: 130,
      name: "Poduri Bhaskar Jaya Sri Sahiti",
      birthDate: "2009-07-09",
      deathDate: null,
      gender: "female",
      parentId: 91,
      spouseId: null,
      generation: 7,
      avatar: "PBJSS",
    },
    {
      id: 131,
      name: "Poduri Yaswanth",
      birthDate: "2013-09-22",
      deathDate: null,
      gender: "male",
      parentId: 91,
      spouseId: null,
      generation: 7,
      avatar: "PY",
    },
    {
      id: 132,
      name: "Poduri Vinay",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 95,
      spouseId: null,
      generation: 7,
      avatar: "PV",
    },
    {
      id: 133,
      name: "Poduri Kasi Viswanath",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 95,
      spouseId: null,
      generation: 7,
      avatar: "PKV",
    },
    {
      id: 134,
      name: "Poduri Meghana",
      birthDate: "2015-03-05",
      deathDate: null,
      gender: "female",
      parentId: 97,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751193871/IMG-20250629-WA0017_ewvfnd.jpg",
    },
    {
      id: 135,
      name: "Poduri Abhi",
      birthDate: "2013-07-07",
      deathDate: null,
      gender: "male",
      parentId: 97,
      spouseId: null,
      generation: 7,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751193871/IMG-20250629-WA0014_gjnzfk.jpg",
    },
    {
      id: 136,
      name: "Poduri Bindu",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 93,
      spouseId: null,
      generation: 7,
      avatar: "PB",
    },
    {
      id: 137,
      name: "Poduri Jahnavi",
      birthDate: "2013-12-6",
      deathDate: null,
      gender: "female",
      parentId: 93,
      spouseId: null,
      generation: 7,
      avatar: "PJ",
    },
    {
      id: 138,
      name: "Poduri Pujya",
      birthDate: "2019-03-22",
      deathDate: null,
      gender: "female",
      parentId: 116,
      spouseId: null,
      generation: 8,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094607/pujya_bq9rzs.jpg",
    },
    {
      id: 139,
      name: "Poduri Chanya",
      birthDate: "2023-08-12",
      deathDate: null,
      gender: "female",
      parentId: 116,
      spouseId: null,
      generation: 8,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094832/chanya_uxtzbr.jpg",
    },
  ],
};
