const familyData = {
  family: [
    {
      id: 1,
      name: "Poduri Appanna",
      birthDate: "",
      deathDate: "",
      gender: "male",
      parentId: null,
      spouseId: 2,
      generation: 1,
      avatar: "PA",
    },
    {
      id: 2,
      name: "Poduri Parvati",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 1,
      generation: 1,
      avatar: "PP",
    },
    {
      id: 3,
      name: "Poduri Shesharao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 1,
      spouseId: 4,
      generation: 2,
      avatar: "PS",
    },
    {
      id: 4,
      name: "Poduri Nagamani",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 3,
      generation: 2,
      avatar: "PN",
    },
    {
      id: 5,
      name: "Poduri Satyanarayana",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 1,
      spouseId: 6,
      generation: 2,
      avatar: "PS",
    },
    {
      id: 6,
      name: "Poduri kameswari",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 5,
      generation: 2,
      avatar: "PK",
    },
    {
      id: 7,
      name: "Poduri Bhaskara Rao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 1,
      spouseId: 8,
      generation: 2,
      avatar: "PB",
    },
    {
      id: 8,
      name: "Poduri Jaya Kumari",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 7,
      generation: 2,
      avatar: "PJK",
    },
    {
      id: 9,
      name: "Poduri Venkateswara Rao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 1,
      spouseId: 10,
      generation: 2,
      avatar: "PVR",
    },
    {
      id: 10,
      name: "Poduri Anantha Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 9,
      generation: 2,
      avatar: "PAL",
    },
    {
      id: 11,
      name: "Poduri Rama Krishna",
      birthDate: "1964-11-12",
      deathDate: null,
      gender: "male",
      parentId: 3,
      spouseId: 12,
      generation: 3,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094831/krishna_lpkq2s.jpg",
    },
    {
      id: 12,
      name: "Poduri Anjali Devi",
      birthDate: "1969-08-11",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 11,
      generation: 3,
      avatar: "PAD",
    },
    {
      id: 13,
      name: "Poduri Lakshmi Narayana",
      birthDate: "1973-09-19",
      deathDate: null,
      gender: "male",
      parentId: 3,
      spouseId: 14,
      generation: 3,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105581/IMG-20250628-WA0003_ybu2au.jpg",
    },
    {
      id: 14,
      name: "Poduri Venkata Lakshmi",
      birthDate: "1982-05-25",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 13,
      generation: 3,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105582/IMG-20250628-WA0001_qumq4v.jpg",
    },
    {
      id: 15,
      name: "Poduri Veera Venkata Mallikarjuna Rao",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 3,
      spouseId: 16,
      generation: 3,
      avatar: "",
    },
    {
      id: 16,
      name: "Poduri Vijaya Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 15,
      generation: 3,
      avatar: "",
    },
    {
      id: 17,
      name: "Poduri Prasad",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 5,
      spouseId: 18,
      generation: 3,
      avatar: "PS",
    },
    {
      id: 18,
      name: "Poduri Vara Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 17,
      generation: 3,
      avatar: "PM",
    },
    {
      id: 19,
      name: "Poduri Appaji",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 5,
      spouseId: 20,
      generation: 3,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751111853/IMG_20250628_172529_jjzgl8.jpg",
    },
    {
      id: 20,
      name: "Poduri Naga Maha Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: null,
      spouseId: 19,
      generation: 3,
      avatar: "PNML",
    },
    {
      id: 21,
      name: "Poduri Venkata Surya Prakash Rao",
      birthDate: "1977-12-07",
      deathDate: null,
      gender: "male",
      parentId: 5,
      spouseId: 22,
      generation: 3,
      avatar: "PVSPR",
    },
    {
      id: 22,
      name: "Poduri Satya Devi",
      birthDate: "1984-06-24",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 21,
      generation: 3,
      avatar: "PSD",
    },
    {
      id: 23,
      name: "Poduri Siva Prasad",
      birthDate: "1975-01-08",
      deathDate: null,
      gender: "male",
      parentId: 7,
      spouseId: 24,
      generation: 3,
      avatar: "PSP",
    },
    {
      id: 24,
      name: "Poduri Jaya Lakshmi",
      birthDate: "1974-05-18",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 23,
      generation: 3,
      avatar: "PJL",
    },
    {
      id: 25,
      name: "Poduri Mohan Kumar",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 7,
      spouseId: 26,
      generation: 3,
      avatar: "PMK",
    },
    {
      id: 26,
      name: "Poduri Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 25,
      generation: 3,
      avatar: "PL",
    },
    {
      id: 27,
      name: "Poduri Appaji",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 9,
      spouseId: 28,
      generation: 3,
      avatar: "PA",
    },
    {
      id: 28,
      name: "Poduri Venkata Lakshmi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 27,
      generation: 3,
      avatar: "PVL",
    },
    {
      id: 29,
      name: "Poduri Kali Vara Prasad",
      birthDate: "1988-06-02",
      deathDate: null,
      gender: "male",
      parentId: 9,
      spouseId: 30,
      generation: 3,
      avatar: "PK",
    },
    {
      id: 30,
      name: "Poduri Lavanya",
      birthDate: "1992-12-06",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 29,
      generation: 3,
      avatar: "PM",
    },
    {
      id: 31,
      name: "Poduri Maruti",
      birthDate: "1981-10-09",
      deathDate: null,
      gender: "male",
      parentId: 9,
      spouseId: 32,
      generation: 3,
      avatar: "PM",
    },
    {
      id: 32,
      name: "Poduri Bharathi Devi",
      birthDate: "1987-06-23",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 31,
      generation: 3,
      avatar: "PBV",
    },
    {
      id: 33,
      name: "Poduri Kumari",
      birthDate: "1989-01-20",
      deathDate: null,
      gender: "female",
      parentId: 11,
      spouseId: null,
      generation: 4,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094831/kumari_frmg5y.jpg",
    },
    {
      id: 34,
      name: "Poduri Lakshmi",
      birthDate: "1991-03-06",
      deathDate: null,
      gender: "male",
      parentId: 11,
      spouseId: null,
      generation: 4,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094831/lakshmiakka_fpserf.jpg",
    },
    {
      id: 35,
      name: "Poduri Seshu Kumar",
      birthDate: "1993-02-01",
      deathDate: null,
      gender: "male",
      parentId: 11,
      spouseId: 36,
      generation: 4,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094830/babi_yp8yfv.jpg",
    },
    {
      id: 36,
      name: "Poduri Pavani",
      birthDate: "1997-01-01",
      deathDate: null,
      gender: "female",
      parentId: null,
      spouseId: 35,
      generation: 4,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094837/pavani_sprtoe.jpg",
    },
    {
      id: 37,
      name: "Poduri Mounika",
      birthDate: "1999-06-28",
      deathDate: null,
      gender: "female",
      parentId: 13,
      spouseId: null,
      generation: 4,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105582/IMG-20250628-WA0000_src81a.jpg",
    },
    {
      id: 38,
      name: "Poduri Sai Lakshmi",
      birthDate: "2002-02-06",
      deathDate: null,
      gender: "female",
      parentId: 13,
      spouseId: null,
      generation: 4,
      avatar: "PC",
    },
    {
      id: 39,
      name: "Poduri Sravani",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 15,
      spouseId: null,
      generation: 4,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105581/IMG-20250628-WA0005_acjpg3.jpg",
    },
    {
      id: 40,
      name: "Poduri Durga Devi",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 15,
      spouseId: null,
      generation: 4,
      avatar: "PDD",
    },
    {
      id: 41,
      name: "Poduri Surya Kala",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 17,
      spouseId: null,
      generation: 4,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751111847/IMG-20250628-WA0013_bparcf.jpg",
    },
    {
      id: 42,
      name: "Poduri Raja Mouli",
      birthDate: "2004-06-13",
      deathDate: null,
      gender: "male",
      parentId: 17,
      spouseId: null,
      generation: 4,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105582/IMG_20250628_153929_o8f2wg.jpg",
    },
    {
      id: 43,
      name: "Poduri Manikanta",
      birthDate: "2003-07-31",
      deathDate: null,
      gender: "male",
      parentId: 19,
      spouseId: null,
      generation: 4,
      avatar: "PM",
    },
    {
      id: 44,
      name: "Poduri Satya Prakash",
      birthDate: "2004-09-24",
      deathDate: null,
      gender: "male",
      parentId: 19,
      spouseId: null,
      generation: 4,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751103832/SAVE_20240725_190616_exhspw.jpg",
    },
    {
      id: 45,
      name: "Poduri Yuvaraj Durga Pavan",
      birthDate: "2004-11-15",
      deathDate: null,
      gender: "male",
      parentId: 21,
      spouseId: null,
      generation: 4,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751111858/Screenshot_2025-06-28-16-39-53-080_com.miui.gallery_hfd4vu.jpg",
    },
    {
      id: 46,
      name: "Poduri Hari Satyanarayana Murthy",
      birthDate: "2007-01-31",
      deathDate: null,
      gender: "male",
      parentId: 21,
      spouseId: null,
      generation: 4,
      avatar: "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751105581/IMG-20250628-WA0004_vwvlhu.jpg",
    },
    {
      id: 47,
      name: "Poduri Tharuni Sri Lakshmi Kumari",
      birthDate: "2005-11-02",
      deathDate: null,
      gender: "female",
      parentId: 23,
      spouseId: null,
      generation: 4,
      avatar: "PTSLK",
    },
    {
      id: 48,
      name: "Poduri Kesava Priya Sri Parvathi",
      birthDate: "2010-04-20",
      deathDate: null,
      gender: "female",
      parentId: 23,
      spouseId: null,
      generation: 4,
      avatar: "PKPSP",
    },
    {
      id: 49,
      name: "Poduri Bhaskar Jaya Sri Sahiti",
      birthDate: "2009-07-09",
      deathDate: null,
      gender: "female",
      parentId: 25,
      spouseId: null,
      generation: 4,
      avatar: "PBJSS",
    },
    {
      id: 50,
      name: "Poduri Yaswanth",
      birthDate: "2013-09-22",
      deathDate: null,
      gender: "male",
      parentId: 25,
      spouseId: null,
      generation: 4,
      avatar: "PY",
    },
    {
      id: 51,
      name: "Poduri Vinay",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 27,
      spouseId: null,
      generation: 4,
      avatar: "PV",
    },
    {
      id: 52,
      name: "Poduri Kasi Viswanath",
      birthDate: "",
      deathDate: null,
      gender: "male",
      parentId: 27,
      spouseId: null,
      generation: 4,
      avatar: "PKV",
    },
    {
      id: 53,
      name: "Poduri Meghana",
      birthDate: "2015-03-05",
      deathDate: null,
      gender: "female",
      parentId: 29,
      spouseId: null,
      generation: 4,
      avatar: "",
    },
    {
      id: 54,
      name: "Poduri Abhi",
      birthDate: "2013-07-07",
      deathDate: null,
      gender: "male",
      parentId: 29,
      spouseId: null,
      generation: 4,
      avatar: "PA",
    },
    {
      id: 55,
      name: "Poduri Bindu",
      birthDate: "",
      deathDate: null,
      gender: "female",
      parentId: 31,
      spouseId: null,
      generation: 4,
      avatar: "PB",
    },
    {
      id: 56,
      name: "Poduri Jahnavi",
      birthDate: "2013-12-6",
      deathDate: null,
      gender: "female",
      parentId: 31,
      spouseId: null,
      generation: 4,
      avatar: "PJ",
    },
    {
      id: 57,
      name: "Poduri Pujya",
      birthDate: "2019-03-22",
      deathDate: null,
      gender: "female",
      parentId: 35,
      spouseId: null,
      generation: 5,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094607/pujya_bq9rzs.jpg",
    },
    {
      id: 58,
      name: "Poduri Chanya",
      birthDate: "2023-08-12",
      deathDate: null,
      gender: "female",
      parentId: 35,
      spouseId: null,
      generation: 5,
      avatar:
        "https://res.cloudinary.com/dv4rmttv6/image/upload/v1751094832/chanya_uxtzbr.jpg",
    },
  ],
};
